#!/usr/bin/env bash
###############################################################################
# post-mr-comment.sh — Post agent results as a GitLab MR comment
#
# Usage:
#   bash ci/scripts/post-mr-comment.sh "Stage Name" artifacts/report.md
###############################################################################
set -euo pipefail

STAGE_NAME="${1:?Usage: post-mr-comment.sh <stage-name> <report-file>}"
REPORT_FILE="${2:?Usage: post-mr-comment.sh <stage-name> <report-file>}"

# Skip if not running in a merge request context
if [[ -z "${CI_MERGE_REQUEST_IID:-}" ]]; then
  echo "Not in MR context — skipping MR comment"
  exit 0
fi

if [[ ! -f "$REPORT_FILE" ]]; then
  echo "Report file not found: $REPORT_FILE — skipping MR comment"
  exit 0
fi

# Truncate report to 60,000 chars (GitLab API limit is 65,535)
REPORT_CONTENT=$(head -c 60000 "$REPORT_FILE")

# Build the comment body
COMMENT_BODY=$(cat <<EOF
## 🤖 Agent Report: ${STAGE_NAME}

**Pipeline:** [#${CI_PIPELINE_ID}](${CI_PIPELINE_URL})
**Job:** [${CI_JOB_NAME}](${CI_JOB_URL})
**Commit:** \`${CI_COMMIT_SHORT_SHA}\`

<details>
<summary>📋 Full Report (click to expand)</summary>

\`\`\`
${REPORT_CONTENT}
\`\`\`

</details>

---
_Generated by AI Agent Pipeline — Stage: ${STAGE_NAME}_
EOF
)

# Post comment via GitLab API
API_URL="${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/merge_requests/${CI_MERGE_REQUEST_IID}/notes"

RESPONSE=$(curl --silent --fail --write-out "\n%{http_code}" \
  --header "PRIVATE-TOKEN: ${GITLAB_API_TOKEN:-${CI_JOB_TOKEN}}" \
  --header "Content-Type: application/json" \
  --data "$(jq -n --arg body "$COMMENT_BODY" '{body: $body}')" \
  "$API_URL")

HTTP_CODE=$(echo "$RESPONSE" | tail -1)
if [[ "$HTTP_CODE" -ge 200 && "$HTTP_CODE" -lt 300 ]]; then
  echo "✓ MR comment posted for stage: ${STAGE_NAME}"
else
  echo "WARNING: Failed to post MR comment (HTTP ${HTTP_CODE})"
  echo "$RESPONSE" | head -5
fi
